---
  version: "3.9"
  services:
  
    latest:
      image: ghcr.io/valorad/pothos-gql-office-racing:latest
      restart: always
      user: "1000"
      ports: 
        - "13000:3000"
      networks:
        - main
  
  # Remember to create this docker network manually!
  networks:
    main:
      external:
        name: main
